# auth_server.py
# This file is the backend server that is used to handle user authentication
# including user registration and login
# currently secured by self-signed certificate generated by OpenSSL
# suggest to use a CA certificate if a FQDN is available

from flask import Flask, request, make_response, jsonify
from flask_cors import CORS

from authenticate import *

from dotenv import load_dotenv
load_dotenv('.env.auth_server')

import os

app = Flask(__name__)
app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')

CORS(app)

# API endpoint that allows POST requests to register users
@app.route("/register", methods=['POST'])
def register():
    if request.method == 'POST':
        # gets the request body in json format
        request_body = request.get_json()

        # get parameters needed for registration
        firstName = request_body['firstName']
        lastName = request_body['lastName']
        username = request_body['username']
        password = request_body['password'] # this password is a hashed password
        salt = request_body['salt'] # the type of the salt here is string

        # register the user
        result = registerUser(firstName, lastName, username, password, salt)
        # print(password)
        # salt1 = salt.encode('utf-8')
        # print(bcrypt.hashpw('123456'.encode('utf-8'), salt1))
        if result == 1:
            response = make_response(jsonify('Successfully registered.', 201))
        elif result == 0:
            response = make_response(jsonify('Username already exists.'), 409)
        else:
            response = make_response(jsonify('Unknown server error, please try again'), 500)

        # sets the CORS header to "*", should be changed to a FQDN if available
        response.headers['Access-Control-Allow-Origin'] = '*'

        return response


# API endpoint that allows POST requests to log users in
@app.route("/login", methods=['POST'])
def login():
    if request.method == 'POST':
        # gets the request body in json format
        request_body = request.get_json()
        
        # get parameters needed for login
        username = request_body['username']
        password = request_body['password']

        # authenticate the user
        auth_value = authUser(username, password)
        if auth_value == 1 and (userid := get_userid(username)) != -2:
            token = issue_token(app.secret_key, username)
            if userid == -2:
                return 
            response = make_response(jsonify({
                'token': token,
                'userid': userid
            }), 200)
        elif auth_value == 0:
            response = make_response(jsonify('Incorrect password.'), 403)
        elif auth_value == -1:
            response = make_response(jsonify('Username not found.'), 401)
        else:
            response = make_response(jsonify('Unknown server error, please try again'), 500)
        
        # sets the CORS header to "*", should be changed to a FQDN if available
        response.headers['Access-Control-Allow-Origin'] = '*'

        return response
    
# API endpoint that allows GET/POST requests retreive salt
@app.route("/salt", methods=['GET', 'POST'])
def salt():
    if request.method == 'GET':
        response = make_response(jsonify(get_rand_salt().decode('utf-8')))

        response.headers['Access-Control-Allow-Origin'] = '*'

        return response
    elif request.method == 'POST':
        request_body = request.get_json()
        username = request_body['username']

        salt = get_salt(username)
        if salt == -1:
            response = make_response(jsonify('Username not found.'), 401)
        elif salt == -2:
            response = make_response(jsonify('Unknown server error, please try again'), 500)
        else:
            response = make_response(jsonify(salt), 200)

        response.headers['Access-Control-Allow-Origin'] = '*'

        return response


if __name__ == "__main__":
    # set SSL with cert.pem and key.pem generated using OpenSSL
    app.run(ssl_context=('cert.pem', 'key.pem'))
    # app.run()
