- hosts: "{{ groups['newmachines'] }}"
  remote_user: "{{ ansible_user }}"
  vars_files: 
    - ./vars/vars.yaml
  tasks:
    - name: Ensure virtualenv is sourced from the .bashrc
      blockinfile:
        path: "{{ remote_prefix }}/{{ ansible_user }}/.bashrc"
        block: |
          # >>> conda initialize >>>
          # !! Contents within this block are managed by 'conda init' !!
          __conda_setup="$('{{ conda_prefix }}/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
          if [ $? -eq 0 ]; then
              eval "$__conda_setup"
          else
              if [ -f "{{ conda_prefix }}/etc/profile.d/conda.sh" ]; then
                  . "{{ conda_prefix }}/etc/profile.d/conda.sh"
              else
                  export PATH="{{ conda_prefix }}/bin:$PATH"
              fi
          fi
          unset __conda_setup
          # <<< conda initialize <<<

        marker: '# ANSIBLE MANAGED BLOCK - virtualenv'
        insertafter: EOF
        create: yes

    - name: Add group anaconda
      ansible.builtin.shell: sudo groupadd anaconda
    - name: Add "{{ ansible_user }}" user to group
      ansible.builtin.shell: sudo usermod -a -G anaconda "{{ ansible_user }}"
    - name: Change ownership of miniconda install to "{{ ansible_user }}"
      ansible.builtin.shell: sudo chown -R "{{ ansible_user }}":anaconda "{{ conda_prefix }}"
    - name: Add everything in the miniconda install to the new anaconda group
      ansible.builtin.shell: sudo chgrp anaconda -R "{{ conda_prefix }}"

    - name: Add conda prefix
      ansible.builtin.shell: "{{ conda_prefix }}/condabin/conda create --prefix {{ conda_prefix }}/envs/{{ conda_environment }} -y"

    - name: Add everything in the miniconda install to the new anaconda group
      ansible.builtin.shell: sudo chgrp anaconda -R "{{ conda_prefix }}"

    - name: Update conda
      ansible.builtin.shell: conda update -n base -c defaults conda