- hosts: "{{ groups['newmachines'] }}"
  remote_user: "{{ ansible_user }}"
  vars_files:
    - ./vars/vars.yaml

  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/Teleoscope/Teleoscope.git'
        dest: ~/Teleoscope
    - name: Install pnpm
      ansible.builtin.shell: npm install -g pnpm
    - name: Install root dependencies
      ansible.builtin.shell: pnpm install
      args:
        chdir: ~/Teleoscope
    - name: Install teleoscope.ca dependencies
      ansible.builtin.shell: pnpm install
      args:
        chdir: ~/Teleoscope/teleoscope.ca
    - name: Generate schemas
      ansible.builtin.shell: pnpm schema
      args:
        chdir: ~/Teleoscope/teleoscope.ca
    - name: Copy auth.py
      ansible.builtin.template:
        src: ./auth.py.j2
        dest: ~/Teleoscope/backend/auth.py
    - name: Copy .env.local
      ansible.builtin.template:
        src: ./.env.local.j2
        dest: ~/Teleoscope/teleoscope.ca/.env.local
    - name: Copy backend .env
      ansible.builtin.template:
        src: ./.env.backend.j2
        dest: ~/Teleoscope/.env

- name: Install Python Dependencies
  ansible.builtin.import_playbook: pythondeps.yaml
